[workspace]

members = [
    "jswt-ast",
    "jswt-codegen",
    "jswt-codeframe",
    "jswt-common",
    "jswt-compiler",
    "jswt-parser",
    "jswt-derive",
    "jswt-tokenizer",
    "jswt-wast"
]