[tasks.coverage]
toolchain = "nightly"
env = { CARGO_INCREMENTAL = 0, RUSTFLAGS = "-Zprofile -Ccodegen-units=1 -Copt-level=0 -Clink-dead-code -Coverflow-checks=off" }
run_task = { name = ["test", "grcov"] }

[tasks.grcov]
install_crate = 'grcov'
command = "grcov"
args = [
    "./target/debug/", 
    "-s", ".", 
    "-t", "html", 
    "--llvm", 
    "--branch", 
    "--ignore-not-existing",
    "-o", "./target/debug/coverage/"
]