[package]
name = "jswt-tokenizer"
version = "0.1.0"
authors = ["Nish Tahir <nishtahir@outlook.com>"]
edition = "2018"

[lib]
doctest = false

[dependencies]
regex = "1.5.4"
lazy_static ="1.4.0"

[dev-dependencies]
pretty_assertions = "1.0.0"