[package]
name = "jswt-tokenizer"
version = "0.1.0"
authors = ["Nish Tahir <nishtahir@outlook.com>"]
edition = "2018"

[lib]
doctest = false

[dependencies]
lazy_static ="1.4.0"
regex = "1.5.4"

[dev-dependencies]
jswt-assert = {path = "../jswt-assert"}
