[package]
name = "jswt-types"
version = "0.1.0"
authors = ["Nish Tahir <nishtahir@outlook.com>"]
edition = "2018"

[lib]
doctest = false

[dependencies]
jswt-common = {path = "../jswt-common"}

[dev-dependencies]
jswt-assert = {path = "../jswt-assert"}