name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup Cargo Make
      run: cargo install --no-default-features --force cargo-make
    - name: Build
      run: cargo make coverage
    - name: Upload to Codecov
      uses: codecov/codecov-action@v2
      with:
        file: ./lcov.info
